### PR TITLE
BLD: Release 4.14

### PR DESCRIPTION
**Pull request by bashtage**
Release 4.14 build

Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bashtage** [comment]
@DanielBok I just pushed 4.14 to PyPI

**Comment by bashtage** [comment]
@conda-forge-admin please rerender

**Comment by bashtage** [comment]
@DanielBok I locally rerendered to update all the CF dependencies

**Comment by DanielBok** [comment]
@bashtage, thanks for your contributions! Since you're the actual package author, would it be fine if I add you as a maintainer to this repo so that going ahead you could also merge in the changes?

**Comment by bashtage** [comment]
@DanielBok Of course.

**Pull request merged**
